import { stringify } from "yaml";
import type { BoundedJob } from "../adapter.js";

export interface IndexedFilter {
  event_name: string;
  indexed_1?: string[];
  indexed_2?: string[];
  indexed_3?: string[];
}

export function renderConfig(job: BoundedJob): string {
  const doc: Record<string, unknown> = {
    name: `chainplot_${job.networkName}`,
    description: "Generated by chainplot; do not edit",
    project_type: "no-code",
    networks: [
      {
        name: job.networkName,
        chain_id: job.chainId,
        rpc: "${RPC_URL}",
      },
    ],
    storage: { postgres: { enabled: true } },
    graphql: { enabled: false },
    contracts: [
      {
        name: job.contractName,
        details: [
          {
            network: job.networkName,
            address: job.addresses.map((a) => a.toLowerCase()),
            start_block: job.jobStart,
            end_block: job.jobEnd,
          },
        ],
        abi: job.abiPath,
        include_events: [...job.events],
        timestamp: true,
      },
    ],
  };
  if (job.indexedFilters && job.indexedFilters.length > 0) {
    const details = (doc.contracts as Array<Record<string, unknown>>)[0]!
      .details as Array<Record<string, unknown>>;
    details[0]!.indexed_filters = job.indexedFilters;
  }
  return stringify(doc, { lineWidth: 0 });
}
